version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: devops-desafio
    ports:
      - 9090:9090
    volumes:
      - metrics:/prometheus/data
    networks:
      - dd

networks:
  dd:

volumes:
  metrics: