version: '3.8'

networks:
  dd:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ~/deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter
      - petshop
    networks:
      - dd

  
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - dd


  pet_shop:
    image: harbor.sflabs.com.br/processo/petshop:latest
    container_name: pet-shop
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - dd


  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3001:3000
    user: '0'
    volumes:
      - ~/deploy/grafana:/var/lib/grafana