- name: Deploy Stack
  hosts: server
  remote_user: ana
  become: yes

  tasks:
    - name: requirements
      apt:
        name: rsync
        state: present


    - name: install docker
      apt:
        name: docker.io
        state: present


    - name: install docker compose
      apt:
        name: docker-compose
        state: present


    - name: create /deploy path
      file:
        path: "deploy"
        state: directory


    - name: create /prometheus path
      file: 
        path: "deploy/prometheus"
        state: directory


    - name: create /grafana path
      file: 
        path: "deploy/grafana"
        state: directory


    - name: copy docker-compose-deploy.yml
      copy:
        src: "../deploy/docker-compose-deploy.yml"
        dest: "deploy/docker-compose-deploy.yml"
      register: config_copy

    
    - name: copy prometheus.yml config
      copy:
        src: "../prometheus/prometheus.yml"
        dest: "deploy/prometheus/prometheus.yml"
      register: config_prometheus_copy


    - name: copy grafana data path
      synchronize:
        src: "../grafana/data"
        dest: "deploy/grafana"